name: weather_app
description: A weather application that allows you to get the current and future weather at your position. Also allows to search others positions.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  auto_route: ^6.0.5
  get_it: ^7.2.0
  flex_color_scheme: ^7.0.0
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  auto_route_generator: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/weather/64x64/day/
    - assets/weather/64x64/night/